/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Comment: typeof import('./src/components/Comment.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    Like: typeof import('./src/components/Base/Like.vue')['default']
    ListSwiper: typeof import('./src/components/List/ListSwiper.vue')['default']
    LoadingUpload: typeof import('./src/components/LoadingUpload.vue')['default']
    Loginabout: typeof import('./src/components/Login/Loginabout.vue')['default']
    LoginDialog: typeof import('./src/components/Login/LoginDialog.vue')['default']
    LoginForm: typeof import('./src/components/Login/LoginForm.vue')['default']
    LoginQr: typeof import('./src/components/Login/LoginQr.vue')['default']
    Lottie: typeof import('./src/components/Lottie.vue')['default']
    NoData: typeof import('./src/components/Lottie/NoData.vue')['default']
    Post: typeof import('./src/components/post/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/Slider.vue')['default']
    Starport: typeof import('vue-starport')['Starport']
    StarportCard: typeof import('./src/components/StarportCard.vue')['default']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    Swiper: typeof import('./src/components/Swiper.vue')['default']
    SwiperCard: typeof import('./src/components/Card/SwiperCard.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
