import antfu from '@antfu/eslint-config'

export default antfu(
  {},
  {
    ignores: [
      'dist',
      'node_modules',
      '.output',
      '.nuxt',
      'content/posts',
      'data',
      'uno.config.ts',
    ],
  },
  {
    rules: {
      'node/prefer-global/process': 'off',
      'no-console': 'off',
			'style/no-tabs': 'off',
			'style/quote-props': 'off',
			'vue/html-indent': 'off',
			'style/indent': 'off',
			'node/prefer-global/process': 'off',
			'node/prefer-global/buffer': 'off',
			'unused-imports/no-unused-vars': 'off',
			'vue/singleline-html-element-content-newline': 'off',
			'ts/no-use-before-define': 'off',
			'no-empty-pattern': 'off',
			'vue/eqeqeq': 'off',
			'ts/no-unsafe-function-type': 'off',
			'unicorn/no-new-array': 'off',
			'ts/no-unused-expressions': 'off',
			'regexp/no-unused-capturing-group': 'off',
			'regexp/no-legacy-features': 'off',
			'eqeqeq': 'off',
			'no-empty': 'off',
			'node/handle-callback-err': 'off',
			'no-case-declarations': 'off',
			'style/no-mixed-spaces-and-tabs': 'off',
			'no-dupe-keys': 'off',
			'regexp/no-dupe-disjunctions': 'off',
			'sort-imports': 'off',
			'unicorn/prefer-dom-node-text-content': 'off',
			'vue/no-use-v-if-with-v-for': 'off',
			'vue/no-unused-refs': 'off',
			'array-callback-return': 'off',
			'regexp/no-dupe-disjunctions': 'off',
			'vue/require-v-for-key': 'off',
			'import/order': 'off',
    },
  },
  {
    files: [
      '*.d.ts',
    ],
    rules: {
      'unused-imports/no-unused-vars': 'off',
      'eslint-comments/no-unlimited-disable': 'off',
    },
  },
)
