/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/E:/MyDev/MyGitHub/cloud-template/src/pages/': RouteRecordInfo<'/E:/MyDev/MyGitHub/cloud-template/src/pages/', '/E:/MyDev/MyGitHub/cloud-template/src/pages', Record<never, never>, Record<never, never>>,
    '/E:/MyDev/MyGitHub/cloud-template/src/pages/[...notFound]': RouteRecordInfo<'/E:/MyDev/MyGitHub/cloud-template/src/pages/[...notFound]', '/E:/MyDev/MyGitHub/cloud-template/src/pages/:notFound(.*)', { notFound: ParamValue<true> }, { notFound: ParamValue<false> }>,
    '/E:/MyDev/MyGitHub/cloud-template/src/pages/echarts': RouteRecordInfo<'/E:/MyDev/MyGitHub/cloud-template/src/pages/echarts', '/E:/MyDev/MyGitHub/cloud-template/src/pages/echarts', Record<never, never>, Record<never, never>>,
  }
}
