/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as ChangelogImport } from "./routes/changelog";
import { Route as ChangelogVersionImport } from "./routes/changelog.$version";
import { Route as ChatImport } from "./routes/chat";
import { Route as ColorsImport } from "./routes/colors";
import { Route as IndexImport } from "./routes/index";
import { Route as NotificationsImport } from "./routes/notifications";
import { Route as ProfileImport } from "./routes/profile";
import { Route as SearchImport } from "./routes/search";

// Create/Update Routes

const ChangelogRoute = ChangelogImport.update({
  path: "/changelog",
  getParentRoute: () => rootRoute,
} as any);

const ChangelogVersionRoute = ChangelogVersionImport.update({
  path: "/changelog/$version",
  getParentRoute: () => rootRoute,
} as any);

const SearchRoute = SearchImport.update({
  path: "/search",
  getParentRoute: () => rootRoute,
} as any);

const ProfileRoute = ProfileImport.update({
  path: "/profile",
  getParentRoute: () => rootRoute,
} as any);

const NotificationsRoute = NotificationsImport.update({
  path: "/notifications",
  getParentRoute: () => rootRoute,
} as any);

const ChatRoute = ChatImport.update({
  path: "/chat",
  getParentRoute: () => rootRoute,
} as any);

const ColorsRoute = ColorsImport.update({
  path: "/colors",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/chat": {
      id: "/chat";
      path: "/chat";
      fullPath: "/chat";
      preLoaderRoute: typeof ChatImport;
      parentRoute: typeof rootRoute;
    };
    "/colors": {
      id: "/colors";
      path: "/colors";
      fullPath: "/colors";
      preLoaderRoute: typeof ColorsImport;
      parentRoute: typeof rootRoute;
    };
    "/notifications": {
      id: "/notifications";
      path: "/notifications";
      fullPath: "/notifications";
      preLoaderRoute: typeof NotificationsImport;
      parentRoute: typeof rootRoute;
    };
    "/profile": {
      id: "/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileImport;
      parentRoute: typeof rootRoute;
    };
    "/search": {
      id: "/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof SearchImport;
      parentRoute: typeof rootRoute;
    };
    "/changelog": {
      id: "/changelog";
      path: "/changelog";
      fullPath: "/changelog";
      preLoaderRoute: typeof ChangelogImport;
      parentRoute: typeof rootRoute;
    };
    "/changelog/$version": {
      id: "/changelog/$version";
      path: "/changelog/$version";
      fullPath: "/changelog/$version";
      preLoaderRoute: typeof ChangelogVersionImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ChangelogRoute,
  ChangelogVersionRoute,
  ChatRoute,
  ColorsRoute,
  NotificationsRoute,
  ProfileRoute,
  SearchRoute,
});

/* prettier-ignore-end */
