/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as ChangelogImport } from "./routes/changelog";
import { Route as ChangelogVersionImport } from "./routes/changelog.$version";
import { Route as ChatImport } from "./routes/chat";
import { Route as ColorsImport } from "./routes/colors";
import { Route as IndexImport } from "./routes/index";
import { Route as MapSecUidImport } from "./routes/map.$secUid";
import { Route as NotificationsImport } from "./routes/notifications";
import { Route as ProfileImport } from "./routes/profile";
import { Route as PublishImport } from "./routes/publish";
import { Route as SearchImport } from "./routes/search";
import { Route as TestCarouselImport } from "./routes/test-carousel";
import { Route as TestUploadImport } from "./routes/test-upload";

// Create/Update Routes

const ChangelogRoute = ChangelogImport.update({
  getParentRoute: () => rootRoute,
  path: "/changelog",
} as any);

const ChangelogVersionRoute = ChangelogVersionImport.update({
  getParentRoute: () => rootRoute,
  path: "/changelog/$version",
} as any);

const SearchRoute = SearchImport.update({
  getParentRoute: () => rootRoute,
  path: "/search",
} as any);

const TestCarouselRoute = TestCarouselImport.update({
  getParentRoute: () => rootRoute,
  path: "/test-carousel",
} as any);

const TestUploadRoute = TestUploadImport.update({
  getParentRoute: () => rootRoute,
  path: "/test-upload",
} as any);

const ProfileRoute = ProfileImport.update({
  getParentRoute: () => rootRoute,
  path: "/profile",
} as any);

const PublishRoute = PublishImport.update({
  getParentRoute: () => rootRoute,
  path: "/publish",
} as any);

const NotificationsRoute = NotificationsImport.update({
  getParentRoute: () => rootRoute,
  path: "/notifications",
} as any);

const ChatRoute = ChatImport.update({
  getParentRoute: () => rootRoute,
  path: "/chat",
} as any);

const ColorsRoute = ColorsImport.update({
  getParentRoute: () => rootRoute,
  path: "/colors",
} as any);

const IndexRoute = IndexImport.update({
  getParentRoute: () => rootRoute,
  path: "/",
} as any);

const MapSecUidRoute = MapSecUidImport.update({
  getParentRoute: () => rootRoute,
  path: "/map/$secUid",
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/changelog": {
      id: "/changelog";
      path: "/changelog";
      fullPath: "/changelog";
      preLoaderRoute: typeof ChangelogImport;
      parentRoute: typeof rootRoute;
    };
    "/changelog/$version": {
      id: "/changelog/$version";
      path: "/changelog/$version";
      fullPath: "/changelog/$version";
      preLoaderRoute: typeof ChangelogVersionImport;
      parentRoute: typeof rootRoute;
    };
    "/chat": {
      id: "/chat";
      path: "/chat";
      fullPath: "/chat";
      preLoaderRoute: typeof ChatImport;
      parentRoute: typeof rootRoute;
    };
    "/colors": {
      id: "/colors";
      path: "/colors";
      fullPath: "/colors";
      preLoaderRoute: typeof ColorsImport;
      parentRoute: typeof rootRoute;
    };
    "/map/$secUid": {
      id: "/map/$secUid";
      path: "/map/$secUid";
      fullPath: "/map/$secUid";
      preLoaderRoute: typeof MapSecUidImport;
      parentRoute: typeof rootRoute;
    };
    "/notifications": {
      id: "/notifications";
      path: "/notifications";
      fullPath: "/notifications";
      preLoaderRoute: typeof NotificationsImport;
      parentRoute: typeof rootRoute;
    };
    "/profile": {
      id: "/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileImport;
      parentRoute: typeof rootRoute;
    };
    "/publish": {
      id: "/publish";
      path: "/publish";
      fullPath: "/publish";
      preLoaderRoute: typeof PublishImport;
      parentRoute: typeof rootRoute;
    };
    "/search": {
      id: "/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof SearchImport;
      parentRoute: typeof rootRoute;
    };
    "/test-upload": {
      id: "/test-upload";
      path: "/test-upload";
      fullPath: "/test-upload";
      preLoaderRoute: typeof TestUploadImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  ChangelogRoute,
  ChangelogVersionRoute,
  ChatRoute,
  ColorsRoute,
  IndexRoute,
  MapSecUidRoute,
  NotificationsRoute,
  ProfileRoute,
  PublishRoute,
  SearchRoute,
  TestCarouselRoute,
  TestUploadRoute,
});

/* prettier-ignore-end */
